### ISSUE TITLE
Wrong git tags 

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/centos7-s2i-nodejs#177]
Specially with 10.x version:

* Github is showing wrong versions and dates:
 
![screenshot_13](https://user-images.githubusercontent.com/6443576/53914090-96471600-403b-11e9-93f4-92842a37620c.png)

My commit is not showing on 10x but is showing on 11x:

![screenshot_14](https://user-images.githubusercontent.com/6443576/53914417-57659000-403c-11e9-930c-28b186945819.png)

![screenshot_15](https://user-images.githubusercontent.com/6443576/53914427-5af91700-403c-11e9-9067-478e541b790a.png)

```console
dba5c66 (HEAD -> 10.x) chore: update to Node.js 10.15.3
7555581 chore: update to Node.js 10.15.2
15db4db (tag: node-10.15.2-1, upstream/10.x) src: add httpd24-libcurl to work with git29 (#176)
22268d6 (tag: node-10.15.2, tag: node-10.15.1) chore: update to Node.js 10.15.1
ef63ae8 src: test to check if scl nodejs pkg exists
9956c9f src: removes rh-nodejs8-runtime package
60570e2 (tag: node-10.15.0) chore: update to Node.js 10.15.0
```

This is a git/github inconsistency only. The published image is using the correct node version:

```console
✔ ~/Desktop/centos7-s2i-nodejs [10.x L|✔] 
18:14 $ docker run -it nodeshift/centos7-s2i-nodejs:10.15.3 bash
bash-4.2$ node --version
v10.15.3
```

We probably need to delete and re-tag some of them starting from 10.15.1 or 10.15.2.

I almost sure that was caused due experiments with automatic changelog creation (exactly 19 days ago):
https://github.com/nodeshift/centos7-s2i-nodejs/issues/97#issuecomment-464116921
And probably after cleanup my local git directory the tags created locally caused something wrong.

**Comment by helio-frota** [comment]
@lance seems that the problem related with `standard changelog` affected 10x tags. The other tags with suffix "-1" has no relation with. And other tags from 11x has no issues.

Affected by the tests done with the  standard-changelog-tool:

`10.15.2` is using the wrong commit `chore: update to Node.js 10.15.1`
`10.15.3` is using the wrong commit  `chore: test change log`

---

Common tags:

`11.10.0` is OK `chore: update to Node.js 11.10.0`
`11.10.1` is OK `chore: update to Node.js 11.10.1`

---

? tags:

`8.15.0-1`  commit `src: add httpd24-libcurl to work with git29`
`10.15.2-1` commit `src: add httpd24-libcurl to work with git29`
`11.9.0-1`  commit `src: add httpd24-libcurl to work with git29`

We are going to follow this pattern of using sufix "-1" ?

**Comment by lance** [comment]
Thanks for taking care of this @helio-frota - I think everything is in order now. Can this be closed?

**Comment by helio-frota** [comment]
@lance yes, I'm closing now thanks!
