### ISSUE TITLE
Support for webpack-dev-server in development mode

### ISSUE THREAD

**Issue by bsharrow** [nodeshift/centos7-s2i-nodejs#178]
The s2i `run` script only supports nodemon for hot deployments when `DEV_MODE=true`.  To use webpack-dev-server, I can set `DEV_MODE=false` and then override `NPM_RUN` but that results in my build and deploy env using different values for `DEV_MODE` and `NODE_ENV`.  

Perhaps the `run` script can be updated with a new environment variable so hot deployments can be started with a different package than nodemon.

**Comment by lholmquist** [comment]
would it make more sense to use the [centos7-s2i-web-app](https://github.com/nodeshift/centos7-s2i-web-app) image?  You still would need to override the NPM_RUN variable in the run script

The only "requirement" here is that in the assemble script, it runs "npm run build", so you would need that defined

**Comment by bsharrow** [comment]
Looks like that will do the trick - I hadn't seen that image as it doesn't look like it's listed in the OCP instance I'm using.  Thanks.
