### ISSUE TITLE
Source Repo from Tutorial gone?

### ISSUE THREAD

**Issue by rhdojun** [nodeshift/centos7-s2i-nodejs#202]
Hi, in the readme you write:

```
oc new-app nodeshift/centos7-s2i-nodejs:latest~https://github.com/nodeshift/nodejs-rest-http
```

But this repo `https://github.com/nodeshift/nodejs-rest-http` doesn't seem to exist anymore. Could you give an update about how to use this s2i repo? Thanks.

**Comment by lholmquist** [comment]
@rhdojun ah yes,  that repo has moved to https://github.com/nodeshift-starters/nodejs-rest-http

nice catch.  I'll update the readme
